const mongoose = require('mongoose');
require('dotenv').config();
const Project = require('./models/Project');
const Node = require('./models/Node');
const { generateResponse } = require('./services/aiService');

const runTest = async () => {
  await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/sidera');
  console.log('Connected to DB');

  try {
    // 1. Create Project
    const project = new Project({ name: "Test Project" });
    await project.save();
    console.log(`1. Created Project: ${project._id}, Name: ${project.name}`);

    // 2. Simulate Chat (First Message)
    const isFirst = true;

    // Mock AI Response (skipping actual API call to save time/tokens if possible, but actually let's use the real service to test Prompt)
    console.log("2. Calling AI Service...");
    const aiData = await generateResponse("What is the speed of light?", true);

    console.log("   AI Data:", JSON.stringify(aiData, null, 2));

    if (aiData.title) {
      console.log(`   Updating Project Title to: ${aiData.title}`);
      const updatedProject = await Project.findByIdAndUpdate(project._id, { name: aiData.title }, { new: true });
      console.log(`3. DB Project Title After Update: "${updatedProject.name}"`);

      if (updatedProject.name === aiData.title) {
        console.log("✅ SUCCESS: Project title updated in DB.");
      } else {
        console.log("❌ FAILURE: Title mismatch.");
      }
    } else {
      console.log("❌ FAILURE: No title generated by AI.");
    }

  } catch (e) {
    console.error(e);
  } finally {
    await mongoose.disconnect();
  }
};

runTest();
