const mongoose = require('mongoose');

const nodeSchema = new mongoose.Schema({
    projectId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Project',
        required: true
    },
    // Merged Question (User) and Answer (AI)
    question: {
        type: String,
        required: true
    },
    answer: {
        type: String,
        required: true
    },
    // Metadata generated by AI
    keywords: [{
        type: String
    }],
    importance: {
        type: String,
        enum: ['Alpha', 'Beta', 'Satellite'],
        default: 'Satellite'
    },
    topicSummary: {
        type: String // Short summary for Topic Flow
    },
    // Visualization
    position: {
        x: { type: Number, default: 0 },
        y: { type: Number, default: 0 },
        z: { type: Number, default: 0 }
    },
    createdAt: {
        type: Date,
        default: Date.now
    }
});

module.exports = mongoose.model('Node', nodeSchema);
