const mongoose = require('mongoose');

const nodeSchema = new mongoose.Schema({
    projectId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Project',
        required: true
    },
    // Merged Question (User) and Answer (AI)
    question: {
        type: String,
        required: true
    },
    answer: {
        type: String,
        required: true
    },
    // Metadata generated by AI
    keywords: [{
        type: String
    }],
    importance: {
        type: Number,
        min: 1,
        max: 5,
        default: 2
    },
    importanceScore: {
        type: Number,
        default: 0
    },
    topicSummary: {
        type: String // Short summary for Topic Flow
    },
    shortTitle: {
        type: String // Ultra-short title (~10 chars) for sidebar
    },
    starLabel: {
        type: String // Short label (~15 chars) for constellation view
    },
    isBookmarked: {
        type: Boolean,
        default: false
    },
    // Context Memory (Vector RAG)
    summary: {
        type: String,
        required: false
    },
    summaryEmbedding: [{
        type: Number
    }],
    fullEmbedding: [{
        type: Number
    }],
    // Visualization
    position: {
        x: { type: Number, default: 0 },
        y: { type: Number, default: 0 },
        z: { type: Number, default: 0 }
    },
    createdAt: {
        type: Date,
        default: Date.now
    }
});

module.exports = mongoose.model('Node', nodeSchema);
